name: dvc-mlops-example
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scikit-learn>=1.1.0
  - dvc>=3.0.0
  - mlflow>=2.0.0
  - flask>=2.0.0
  - pyyaml>=6.0
  - joblib>=1.1.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
