train:
  alpha: 0.1
  max_iter: 1000
  random_state: 42
  test_size: 0.2
  model_type: "ridge"  # "linear", "ridge", "lasso"

evaluate:
  metrics:
    - "mse"
    - "r2_score"
    - "mae"
    - "rmse"
